version: '3'

services:
  glances:
    image: nicolargo/glances:latest-full
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock
      - type: bind
        source: ${PWD}/glances.conf
        target: /glances/conf/glances-abc.conf
        read_only: true
    environment:
      - "GLANCES_OPT=--export influxdb -C /glances/conf/glances-abc.conf"
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:1.8-alpine
    restart: unless-stopped
    environment:
      - INFLUXDB_DB=glances
      - INFLUXDB_USER=glances
      - INFLUXDB_PASSWORD=glances
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
volumes:
  influxdb_data: {}
