version: '3.9'
services:
  glances:
    image: nicolargo/glances:latest-full
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock
    environment:
      - "GLANCES_OPT=--export influxdb"
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:1.8-alpine
    restart: unless-stopped
    environment:
      - INFLUXDB_DB=glances
      - INFLUXDB_USER=root
      - INFLUXDB_PASSWORD=root
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
volumes:
  influxdb_data: {}
